config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :confirmation_emails

  root 'maps#index'

  resources :maps

end

app/models/confirmation_email.rb
class ConfirmationEmail < ActiveRecord::Base
end

app/models/user.rb
require 'geocoder'
class User < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	# before_action do
 #      @gmap_api_key = ENV["GOOGLE_API_MAPS_KEY"]
 #  end 
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confirmation_emails_controller.rb
class ConfirmationEmailsController < ApplicationController
	before_action :set_confirmation_email, only: [:show, :edit, :update, :destroy]

	def index
		@confirmation_emails = ConfirmationEmail.all
	end

  def new
    @confirmation_email = ConfirmationEmail.new
    @address = params["address"]
    @name = params["name"]
    binding.pry
  end

	def show

	end

	def create
		@confirmation_email = ConfirmationEmail.new(confirmation_email_params)

			respond_to do |format|
				if @confirmation_email.save
						MidwaysEmail.confirmation_email(@confirmation_email).deliver
					format.html { redirect_to @confirmation_email, notice: 'User was successfully created.' }
  				format.json { render :show, status: :created, location: @confirmation_email }
				else
  				format.html { render :new }
  				format.json { render json: @confirmation_email.errors, status: :unprocessable_entity }
				end
			end
	end

	def update
  	respond_to do |format|
      if @confirmation_email.update(confirmation_email_params)
        format.html { redirect_to @confirmation_email, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @confirmation_email }
      else
        format.html { render :edit }
        format.json { render json: @confirmation_email.errors, status: :unprocessable_entity }
      end
    end
  end

		def destroy
	    @confirmation_email.destroy
	    respond_to do |format|
	      format.html { redirect_to confirmation_emails_url, notice: 'User was successfully destroyed.' }
	      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_confirmation_email
      @confirmation_email = ConfirmationEmail.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def confirmation_email_params
      params.require(:confirmation_email).permit(:your_name, :your_email, :recipients_name, :recipients_email)
    end
end

app/controllers/locuapi_controller.rb
require 'httparty'
require 'pry'
require 'json'

class LocuapiController < ApplicationController

  def index
  # uncommented react.js in app/assest/javascript/application.js MIGHT be an issue later.
  # Not sure why I needed to uncomment this inorder for index page to load

  # deleted work using httparty trying to call Locu api. Issue is that V2 of the api is not easy to work with
  # decided to use google places api instead
	

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	skip_before_action :verify_authenticity_token

  @@client = GooglePlaces::Client.new(ENV['GOOGLE_API_MAPS_KEY'])
  # client is a method off of the google places gem
  # were just creating a new client from the google places gem
  # and using our API_key

	def index
		@maps_api_key = ENV["GOOGLE_API_MAPS_KEY"]
    @clcktl_ui = ENV["CLICKATELL_UI"]
    @clcktl_route_id = ENV["CLICKATELL_ROUTE_ID"]
    @clcktl_addr = ENV["CLICKATELL_ADDR"]
    @clcktl_from_no = ENV["CLICKATELL_FROM_NO"]
    # binding.pry
    render :index
  end

  def create
  	lat = params["destinationLat"].to_f
  	lng = params["destinationLng"].to_f
  	meetTime = params["meetTime"].to_i
  	cuisine = params["cuisine"].delete! '\"'
  	# binding.pry
  	# get info from google places
  	@results = @@client.spots(lat, lng, :radius => 200, :keyword => cuisine, :types => 'restaurant')
    # binding.pry
    if @results.length < 3 
      @results = @@client.spots(lat, lng, :radius => 400, :keyword => cuisine, :types => 'restaurant')
      puts 400
    end
  	# binding.pry
  	# @name = "peter"
  	# @spots = results.flatten
  	# put it in a variable

  	render :create
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  @client = GooglePlaces::Client.new(ENV['GOOGLE_PLACES_API_KEY'])
  # client is a method off of the google places gem
  # were just creating a new client from the google places gem
  # and using our API_key

  # GET /users
  # GET /users.json
  def index
    @client.spots(-33.8670522, 151.1957362, :types => 'restaurant')
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password, :lat, :long, :address)
    end
end

app/controllers/welcome_controller.rb
require 'json'
# require 'pry'
# require 'httparty'

class WelcomeController < ApplicationController

	# response = HTTParty.get('')


	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locuapi_helper.rb
module LocuapiHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/confirmation_emails/_form.html.erb
<%= form_for(@confirmation_email) do |f| %>
  <% if @confirmation_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@confirmation_email.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @confirmation_email.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :your_name %><br>
    <%= f.text_field :your_name %>
  </div>
  <div class="field">
    <%= f.label :your_email %><br>
    <%= f.text_field :your_email %>
  </div>
  <div class="field">
    <%= f.label :recipients_name %><br>
    <%= f.text_field :recipients_name %>
  </div>
  <div class="field">
    <%= f.label :recipients_email %><br>
    <%= f.text_field :recipients_email %>
  </div>
  <!-- need to add link here that sutopopulates -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/confirmation_emails/new.html.erb
<h1>Email send out form</h1>

<%= render 'form' %>

<h3><%= @name %></h3>
<h3><%= @address %></h3>

<%= link_to 'Back', confirmation_emails_path %>

app/views/confirmation_emails/show.html.erb
show.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>Midways</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Quattrocento' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhkRkWThkV6APyvLBxY0IGawNC_N87VXI&signed_in=false&callback=initMap&libraries=geometry" async defer></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
</html>

app/views/locuapi/index.html.erb
<%= @response %>

app/views/maps/index.html.erb
<div class="container">
    <div class="col-md-3">
    <header><h1>Midways</h1></header>
      <form id="preferences" class="form-horizontal" action="#">

        <label for="astart" class="mdl-textfield__label">Your location</label>      
        <div class="form-group">
            <div class="col-sm-12">
              <input type="text" class="form-control" id="start" placeholder="Your Address" value=''>
            </div>
        </div>

        <label for="bstart" class="mdl-textfield__label">Friend's location</label>
        <div class="form-group">
            <div class="col-sm-12">
              <input type="text" class="form-control" id="end" placeholder="Friend's Address" value=''>
            </div>
        </div>

        <label class="mdl-textfield__label" for="cuisine">What would you like to eat?</label>
          <select class="form-control" id="cuisine">
            <option value="barbecue">Barbecue</option>
            <option value="french">French</option>
            <option value="indian">Indian</option>
            <option value="japanese">Japanese</option>
            <option value="pizza">Pizza</option>
            <option value="steak">Steak</option>
            <option value="thai">Thai</option>
            <option value="american">American</option>
            <option value="chinese">Chinese</option>
            <option value="hamburger">Hamburger</option>
            <option value="italian">Italian</option>
            <option value="mexican">Mexican</option>
            <option value="seafood">Seafood</option>
          </select>

      <div class="form-group">
        <div class="col-sm-offset-8 col-sm-4">
          <button type="submit" id="submit" value="Submit" class="btn btn-default plan-it">Plan It</button>
        </div>
      </div>

       </form>
       <div id="cardTest"></div> 
      </div>

    <div class="map">  
      <div id="map"></div>
    </div>  
   </div>

app/views/midways_email/midways_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
<h1>Hi <%= @confirmation_email %></h1>
 <p>
      Sample mail sent using smtp.
    </p>	
</body>
</html>

app/views/midways_email/midways_email.text.erb
Hi <%= @user.name %>
Sample mail sent using smtp. 

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :your_name %><br>
    <%= f.text_field :your_name %>
  </div>
  <div class="field">
    <%= f.label :your_email %><br>
    <%= f.text_field :your_email %>
  </div>
  <div class="field">
    <%= f.label :recipient_name %><br>
    <%= f.text_field :recipient_name %>
  </div>
  <!-- need to add link here that sutopopulates -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1> TESTING START</h1>

<% @test.each do |test| %>

  <div>
   <%= test.name %> 
  </div>
  <img src= "<%= test.icon %>">
  </img>

<% end %>

  <h1> TESTING END</h1>


<h1>atm test</h1>

<% @atm.each do |atm| %>

  <div>
   <%= atm.name %> 
  </div>
  <img src= "<%= atm.icon %>">
  </img>

<% end %>

<h1>Testing bars</h1>

<% @bars.each do |bar| %>

  <div>
   <%= bar.name %> 
  </div>
  <img src= "<%= bar.icon %>">
  </img>

<% end %>

<h1>END TESTING BARS</h1>
<% @spots.each do |spot| %>

  <div class="spot">
   <%= spot.name %> 
  </div>
  <img src= "<%= spot.icon %>">
  </img>

<% end %>

<h1> TESTING ITALIAN RESTURANT BELOW </h1>

<% @italian.each do |italian| %>

  <div>
   <%= italian.name %> 
  </div>
  <img src= "<%= italian.icon %>">
  </img>

<% end %>

<h1> TESTING FRENCH RESTURANT BELOW </h1>

<% @french.each do |french| %>

  <div>
   <%= french.name %> 
  </div>
  <img src= "<%= french.icon %>">
  </img>

<% end %>


<h1> TESTING MEXICAN RESTURANT BELOW </h1>

<% @mexican.each do |mexican| %>

  <div>
   <%= mexican.name %> 
  </div>
  <img src= "<%= mexican.icon %>">
  </img>

<% end %>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Password</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.latitude %></td>
        <td><%= user.longitude %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @user.latitude %>
</p>

<p>
  <strong>Long:</strong>
  <%= @user.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<% @result.each do |business| %>
	<div>
		<h3><%= business.name %></h3>
		<p><%= business.location.display_address[0] %></p>
		<img src="<%= business.image_url %>" alt=""><br>
		<img src="<%= business.rating_img_url %>" alt="">
		<p>based on <%= business.review_count %> reviews</p>
	</div>
<% end %>